In [2]:
import numpy as np


In [3]:
# create from ,list

arr=np.array([1,2,3,4,5,6])
print(arr, type(arr), arr.dtype)

arr2=np.array([1,2,3,4,"Prime"]) # it will convert all data into string beacuse it contains only same type of data
print(arr2, type(arr2), arr2.dtype)

[1 2 3 4 5 6] <class 'numpy.ndarray'> int64
['1' '2' '3' '4' 'Prime'] <class 'numpy.ndarray'> <U21


In [4]:
# 2d array

arr2D=np.array([[1,2,3],[4,5,6],[7,8,9], [10,11,12]])
print(arr2D,arr2D.shape)# (row, col)(4,3)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] (4, 3)


In [ ]:
# create array from scratch

arr1=np.zeros((2,3), dtype="int64")
print(arr1, arr1.shape)

arr2=np.ones((2,3), dtype="int64")
print(arr2, arr1.shape)

arr3=np.full((3, 4),100)# prefill with value
print(arr3)

#identity metric
arr4=np.eye((3))
print(arr4)

#range fun

arr5=np.arange(1,10,2)
print(arr5)

#linspace
arr6=np.linspace(0,100,4) # evenly spaced arrays
print(arr6)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1 1 1]
 [1 1 1]] (2, 3)
[[100 100 100 100]
 [100 100 100 100]
 [100 100 100 100]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[1 3 5 7 9]
[  0.          33.33333333  66.66666667 100.        ]


In [16]:
#Properties of Numpy array

arr=np.array([1,2,3,4,50,56,67])

print(arr.shape)
print(arr.size)
print(arr.dtype)# data type
print(arr.ndim) #dimention

# convert array into float

float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)

(7,)
7
int64
1
[ 1.  2.  3.  4. 50. 56. 67.] float64
