Important operations on Numpy array

1.Reshaping of array

In [1]:
import numpy as np
arr=np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)

reshapedarr=arr.reshape((3,2))
print(reshapedarr, reshapedarr.shape)

# convert 2d arr into 1 d arr
flattend=arr.flatten()
print(flattend, flattend.shape)


[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


2.Indexing


In [2]:
arr=np.array([1,2,3,4,5,6])
# print(arr[0])
# print(arr[5])

arr2=np.array([[1,2,3],[4,5,6]])
print(arr2[0][2])
print(arr2[1][1])


#fancy indexing

idx=[0,1,3]
print(arr[idx])

#boolean indexing

print(arr[arr>3])
print(arr[arr%2==0])

3
5
[1 2 4]
[4 5 6]
[2 4 6]


Slicing

In python list-slicing create a copy(new array)
But in numpy create a view- which is the sub part of array- It does not create any copy this is why it is fats it does not take memory for new copy.


In [9]:
arr=np.array([1,2,3,4,5])
sublist=arr[1:3] #[2,3]
sublist[0]=200# if we change the value of sub array it will change the original arr also beacuse it doe not creeate copy but create a view

# if want to create copy 
# sublist=arr[1:3].copy()

print(sublist)
print(arr)
# print(arr[0:2])
# print(arr[0::2])

[200   3]
[  1 200   3   4   5]
