Axes in multi dimenional array

- If we want ot feed black and white image then we use 2d array (0-255)
- For Colored image we use 3d array (r,g,b)- we send 3 matrix


1D array----1 axes=axis 0
2D array----2 axes=axis 0 and 1(rows-vertically, col-horizontal)
3D array----3 axes= axis 0,1,2(debth, row, col)

In [ ]:
# multidimentional array
import numpy as np 

arr2d=np.array([[1,2,3],[4,5,6,],[7,8,9]])

print(arr2d)
print(np.sum(arr2d))# sum of all num

# sum of all cols- use axis 0- vertical
sum_col=np.sum(arr2d, axis=0)# col
print(sum_col)

# sum of rows - use axis 1- horizontal

sum_row=np.sum(arr2d, axis=1)# row
print(sum_row)

# slice axis wise
print(arr2d[0:2,1:2])# 0:2 means rows, 1:2 means range of colmns


[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


3D array

In [19]:
arr3d=np.array([[[1,2],[3,4],[5,6]],[[7,8],[9,10],[11,12]]]) # 2x3x2

print(arr3d, arr3d.shape)

# get 4 elm
print(arr3d[0][1][1])
print(arr3d[1][1][0])# 9

#slicing
print(arr3d[:,0,:])# extract 1 row from both axis
print(arr3d[:,:,0:1]) # firct col from both table

# replace values
arr3d[:,:,0:1]=99
print(arr3d)


[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] (2, 3, 2)
4
9
[[1 2]
 [7 8]]
[[[ 1]
  [ 3]
  [ 5]]

 [[ 7]
  [ 9]
  [11]]]
[[[99  2]
  [99  4]
  [99  6]]

 [[99  8]
  [99 10]
  [99 12]]]
