Vectorization and broadcasting


In [1]:
# vetorization

import numpy as np

arr=np.array([1,2,4,5,6])
arr2=np.array([1,2,4,5,6])
print(arr**2)
print(arr+arr2)

[ 1  4 16 25 36]
[ 2  4  8 10 12]


Boradcasting -scaling
Make the size compatible with larger array size [1,2,3] (vector)+ 1 (scalar)=[1,1,1](broadcasting)



In [2]:
# Boradcasting 

arr=np.array([1,2,4,5,6])
arr2=np.array([[1,2,4,5,6],[1,2,4,5,6]])
# print(arr+5)

print(arr.shape)
print(arr2.shape)

print(arr+arr2)

(5,)
(2, 5)
[[ 2  4  8 10 12]
 [ 2  4  8 10 12]]


Vector Normalization

To implement in desired range(0,1)

std mornalization= (arr-mean)/std deviation

Normalization is used to scale data, and it is very useful in data science, machine learning, and numerical computing.

✅ Why we use normalization?

Brings all values to a similar scale
Different features can have different ranges (e.g., age 1–100, salary 10k–1M).
Normalization converts them to a common scale, usually around 0 mean and 1 std deviation.


In [3]:
# normalize

arr=np.array([[1,2],[3,4]])

mean=np.mean(arr)
std_dev=np.std(arr)

nomalized_arr=(arr-mean)/std_dev
print(nomalized_arr)

print(mean)
print(std_dev)

[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]
2.5
1.118033988749895


In [19]:
arr=np.array([10,-1,22,-3,4,4])

print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))  # make values positive


[-3 -1  4 10 22]
[-3 -1  4  4 10 22]
[10  1 22  3  4  4]
